### ISSUE TITLE
Issues with DISPLAY and DEVICE

### ISSUE THREAD

**Issue by umbraesoulsbane** [belane/docker-bloodhound#3]
I have been trying to get this to run. I am wondering if this is a Windows issue as some of the commands I have never used before. I am trying to do this with a Docker-Compose, but get the same types of errors running the command line.

Here is my Docker-Compose:
`version: '3.3'

services:

    bloodhound:
        image: belane/bloodhound
        environment: 
            - "DISPLAY=unix$DISPLAY"
        devices:
            - "/dev/dri:/dev/dri"
        volumes:
            - ./srv/data:/data
        ports:
            - "7474:7474"
`
The error I get is:

> ERROR: for 6aaebf9c3a15_bloodhoundad_bloodhound_1  Cannot start service bloodhound: linux runtime spec devices: error gathering device information while adding custom device "/dev/dri": no such file or directory

If I comment out device it will start then immediately die. It does give this warning:

> WARNING: The DISPLAY variable is not set. Defaulting to a blank string.

And this is the log after it starts:

`Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /etc/neo4j
  logs:         /var/log/neo4j
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/run/neo4j
Starting Neo4j.
Started neo4j (pid 62). It is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /var/log/neo4j/neo4j.log for current status.
Starting ...
First run takes some time
*** Log in with bolt://127.0.0.1:7687 (neo4j:blood) ***`

Any idea what I need to do to get this running?

**Comment by umbraesoulsbane** [comment]
I was able to get the WARNING on DISPLAY to go away by delimiting the $

`- "DISPLAY=unix$$DISPLAY"`

Not sure if that is proper or not, but it did not resolve any of the issues related to the container stopping and the docker logs did not change.

**Comment by xbytemx** [comment]
Hi, I was able to run the docker with the default configuration, but first I need to allow my user to the xserver with 
```
xhost +local:$(id -nu)
```

If you want to deny it after using the container, then:

```
xhost -local:$(id -nu)
```

Cheers
