### ISSUE TITLE
OpenJDK Docker Image Deprecated

### ISSUE THREAD

**Issue by litobro** [belane/docker-bloodhound#9]
The OpenJDK docker images are now deprecated as per the notice on [Docker hubs](https://hub.docker.com/_/openjdk). 

I have rebuilt this image using debian:stable-slim and installed a JDK from apt-get repositories, and it seems to be an acceptable alternative.

**Comment by belane** [comment]
Thanks @litobro, I'll take a look

**Comment by litobro** [comment]
I opened a PR after reconfiguring the Dockerfile to the latest versions. https://github.com/belane/docker-bloodhound/pull/10
